[tool.black]
line-length = 120
target-version = ["py311"]
# English: Exclude virtualenvs, build outputs, MLflow runs, and any vendored libs.
extend-exclude = '''
(
  ^\.venv
 |^venv
 |^env
 |^build
 |^mlruns
 |^src/package
 |^docker
 |^infra
 |^model_dir
)
'''