[tool.black]
# English: Keep the same formatting width as local
line-length = 120
target-version = ["py311"]

# English: Do not format virtualenvs, build outputs, MLflow runs, or vendored libs
extend-exclude = """
(
  ^\\.venv
 |^venv
 |^env
 |^build
 |^dist
 |^mlruns
 |^src/package
 |^docker
 |^infra
 |^model_dir
)
"""
