GBFS_STATION_INFORMATION_DAILY_SCHEDULE = "22 1 * * *"
DBT_STATION_TOPOLOGY_DAILY_SCHEDULE = "22 2 * * *"
DBT_DIAGNOSTIC_DAILY_SCHEDULE = "47 2 * * *"
HOLIDAY_YEARLY_SCHEDULE = "11 2 1 1 *"
OFFLINE_MODEL_RETRAINING_DAILY_SCHEDULE = "30 3 * * *"

WEATHER_10MIN_SCHEDULE = "7-59/10 * * * *"
DBT_WEATHER_REFRESH_10MIN_SCHEDULE = "8-59/10 * * * *"

GBFS_STATION_STATUS_5MIN_SCHEDULE = "*/5 * * * *"
DBT_STATION_STATUS_HOTPATH_5MIN_SCHEDULE = "1-59/5 * * * *"
DBT_FEATURE_BUILD_5MIN_SCHEDULE = "4-59/5 * * * *"
DBT_QUALITY_HOURLY_SCHEDULE = "13 * * * *"

SERVING_PREDICTION_SCHEDULE = "2-59/15 * * * *"
SERVING_QUALITY_SCHEDULE = "3-59/15 * * * *"
SERVING_METRICS_SCHEDULE = "42 * * * *"
SERVING_PSI_SCHEDULE = "12 * * * *"
