{{ config(
    materialized='view'
) }}

with ranked as (
    select
        city,
        dt,
        station_id,
        capacity,
        lat,
        lon,
        bikes,
        docks,
        minutes_since_prev_snapshot,
        util_bikes,
        util_docks,
        delta_bikes_5m,
        delta_docks_5m,
        roll15_net_bikes,
        roll30_net_bikes,
        roll60_net_bikes,
        roll15_bikes_mean,
        roll30_bikes_mean,
        roll60_bikes_mean,
        nbr_bikes_weighted,
        nbr_docks_weighted,
        has_neighbors_within_radius,
        neighbor_count_within_radius,
        hour,
        dow,
        is_weekend,
        is_holiday,
        temperature_c,
        humidity_pct,
        wind_speed_ms,
        precipitation_mm,
        weather_code,
        hourly_temperature_c,
        hourly_humidity_pct,
        hourly_wind_speed_ms,
        hourly_precipitation_mm,
        hourly_precipitation_probability_pct,
        hourly_weather_code,
        row_number() over (
            partition by city, station_id
            order by dt desc
        ) as row_num
    from {{ ref('feat_station_snapshot_5min') }}
)
select
    city,
    dt,
    station_id,
    capacity,
    lat,
    lon,
    bikes,
    docks,
    minutes_since_prev_snapshot,
    util_bikes,
    util_docks,
    delta_bikes_5m,
    delta_docks_5m,
    roll15_net_bikes,
    roll30_net_bikes,
    roll60_net_bikes,
    roll15_bikes_mean,
    roll30_bikes_mean,
    roll60_bikes_mean,
    nbr_bikes_weighted,
    nbr_docks_weighted,
    has_neighbors_within_radius,
    neighbor_count_within_radius,
    hour,
    dow,
    is_weekend,
    is_holiday,
    temperature_c,
    humidity_pct,
    wind_speed_ms,
    precipitation_mm,
    weather_code,
    hourly_temperature_c,
    hourly_humidity_pct,
    hourly_wind_speed_ms,
    hourly_precipitation_mm,
    hourly_precipitation_probability_pct,
    hourly_weather_code
from ranked
where row_num = 1
