name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write   # needed for OIDC
  contents: read

env:
  AWS_REGION: ca-central-1
  AWS_ROLE_ARN: arn:aws:iam::387706002632:role/gh-oidc-deployer

jobs:
  oidc-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      - name: Prove we assumed role
        run: aws sts get-caller-identity

  terraform-validate:
    runs-on: ubuntu-latest
    needs: [oidc-smoke]
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: tf-validate-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt & validate
        working-directory: infra/terraform
        run: |
          terraform init -reconfigure
          terraform fmt -check -recursive
          terraform validate
