name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write    # needed for OIDC (only used on push to main)
  contents: read

env:
  AWS_REGION: ca-central-1
  AWS_ROLE_ARN: arn:aws:iam::387706002632:role/gh-oidc-deployer

jobs:
  # 仅在 push 到 main 时运行：验证 OIDC 能 Assume Role + Terraform 连接远端 backend
  oidc-smoke:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Prove we assumed role
        run: aws sts get-caller-identity

  # PR 和 push 都运行：在 PR 上禁用 backend（不需要 AWS），在 main 上用远端 backend
  terraform-validate:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # 在 PR 上：不需 AWS、不连接 S3 后端
      - name: Terraform fmt & validate (PR)
        if: github.event_name == 'pull_request'
        working-directory: infra/terraform
        run: |
          terraform init -backend=false
          terraform fmt -check -recursive
          terraform validate

      # 在 push 到 main 上：走 OIDC，连接远端 backend
      - name: Configure AWS credentials (OIDC)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: tf-validate-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Terraform fmt & validate (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        run: |
          terraform init -reconfigure
          terraform fmt -check -recursive
          terraform validate
