# .github/workflows/groundtruth-cron.yml
name: Build Ground Truth (every 30m)

on:
  schedule:
    - cron: "*/30 * * * *"     # Run every 30 minutes (UTC)
  workflow_dispatch:            # Allow manual run

env:
  AWS_REGION: ${{ vars.AWS_REGION }}   # Change if needed
  ENDPOINT_NAME: ${{ vars.ENDPOINT_STAGING }}  # <-- set your endpoint name
  SM_EXECUTION_ROLE_ARN: ${{ secrets.SM_EXECUTION_ROLE_ARN }}

jobs:
  build-gt:
    runs-on: ubuntu-latest

    # Minimal permissions for GitHub OIDC -> AWS
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          # Install libraries required by your script
          pip install boto3 pandas pyarrow

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-${{ github.run_id }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Compute time window (UTC) in PowerShell
        # Use PowerShell to compute start/end with hour precision
        shell: pwsh
        run: |
          # Compute "start" as current UTC time minus 2 hours, hour-granularity
          $nowUtc = [DateTime]::UtcNow
          $start  = $nowUtc.AddHours(-2).ToString('yyyy-MM-dd-HH')  # format required by your script
          $end    = $nowUtc.ToString('yyyy-MM-dd-HH')               # format required by your script

          # Export to GITHUB_ENV for later steps (bash will read START/END)
          "START=$start" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "END=$end"     | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Run build_GroundTruth_from_parquet.py
        # IMPORTANT: update the relative path below to where the file lives in your repo
        run: |
          python src/monitoring/build_GroundTruth_from_parquet.py \
            --start "$START" \
            --end "$END" \
            --endpoint "$ENDPOINT_NAME"
