name: Publish Custom Model Metrics

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ca-central-1
      BUCKET: mlops-bikeshare-387706002632-ca-central-1
      ENDPOINT: bikeshare-staging
      QUALITY_PREFIX: monitoring/quality/city=nyc   
      THRESHOLD: "0.5"
      CITY: "nyc"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-${{ github.run_id }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Publish metrics to CloudWatch
        run: |
          python src/monitoring/metrics/publish_custom_metrics.py \
            --bucket "$BUCKET" \
            --quality-prefix "$QUALITY_PREFIX" \
            --endpoint "$ENDPOINT" \
            --region "$AWS_REGION" \
            --threshold "$THRESHOLD" \
            --city-dimension "$CITY"