# .github/workflows/quality.yml
name: quality-backfill
on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch: {}

concurrency:
  group: quality-backfill
  cancel-in-progress: true

env:
  AWS_REGION: ${{ vars.AWS_REGION }}  
  SM_ENDPOINT: ${{ vars.ENDPOINT_STAGING }}         

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configure AWS OIDC -> role that has S3/Athena/SageMakerRuntime perms
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-${{ github.run_id }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Quality Backfill
        run: |
          python -m src.monitoring.quality_backfill
